Learning Numpy

In [1]:
import numpy as np

Array creation with numpy:

In [5]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [ ]:
a = np.ones((4, 4))

b= np.zeros((4, 4))

a,b

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

In [54]:
a = np.arange(0,20,2)


b= np.arange(1,17,1)
a, b

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]))

In [24]:
a = np.random.rand(4,3)
a

array([[0.8895059 , 0.30230751, 0.33715304],
       [0.86738418, 0.67081818, 0.55927302],
       [0.19502961, 0.1997908 , 0.60702535],
       [0.43021766, 0.74235116, 0.49711505]])

In [17]:
b = np.linspace(1,16,16)
b

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16.])

In [99]:
a = np.linspace(1,16,16)

a = np.reshape(a,(4,4))

a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

Array indexing and slicing:

In [72]:
a = np.linspace(1,16,16)
a = np.reshape(a,(4,4))

print(a.size)
print(a.shape)
print(a.ndim)

print(a[:,2]) # from all raws, column 2
print("----------------------")

print(a[0,:]) # from row 0, all columns
print("----------------------")

print(a[0:2,0:2]) # from row 0 to 1, column 0 to 1
print("----------------------")

print(a[3,:]) # from row 3, all columns
print("----------------------")

print(a[0:2,1:3]) # from row 0 to 1, column 1 to 2
print("----------------------")

print (a[a>5]) # all elements greater than 5 (boolean masking)

16
(4, 4)
2
[ 3.  7. 11. 15.]
----------------------
[1. 2. 3. 4.]
----------------------
[[1. 2.]
 [5. 6.]]
----------------------
[13. 14. 15. 16.]
----------------------
[[2. 3.]
 [6. 7.]]
----------------------
[ 6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]


Vectorized operations:

In [ ]:
a= np.arange(1,17,1)
a= np.reshape(a,(4,4))

b=np.array([1,2,3,4])

print(a+b)                      #broadcasting
print("----------------------")
print(a*b)
print("----------------------")
print(a@b) # matrix multiplication
print("----------------------")
print(a*2) # multiply each element by 2
print("----------------------")
print(a.mean()) # mean of all elements
print("----------------------")
print(a.mean(axis=0)) # mean of each column
print("----------------------")
print(a.mean(axis=1)) # mean of each row
print("----------------------")
print(a.sum()) # sum of all elements
print("----------------------")
print("----------------------")


[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]
 [14 16 18 20]]
----------------------
[[ 1  4  9 16]
 [ 5 12 21 32]
 [ 9 20 33 48]
 [13 28 45 64]]
----------------------
[ 30  70 110 150]
----------------------
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
----------------------
8.5
----------------------
[ 7.  8.  9. 10.]
----------------------
[ 2.5  6.5 10.5 14.5]
----------------------
136
----------------------
----------------------
[ 6  7  8  9 10 11 12 13 14 15 16]


Hands-On Lab Task :
 1- Create a 2D array of shape (4, 4) filled with values 1-16 and print its shape and dtype
 2- Use slicing to extract the second column and the last row
 3- Use a boolean mask to select all values greater than the array's mean.
 4- Add a 1D row array to every row of a 2D array using broadcasting, and verify the result manually.

In [97]:
#1 
a= np.arange(1,17,1)
a= np.reshape(a,(4,4))

print("array a: \n" ,a)
print("----------------------")

print( "array a's shape: " ,a.shape)
print("----------------------")

print("array a's type: " ,type(a))
print("----------------------")

print("array's element a[0,0] type: " ,type(a[0,0]))
print("----------------------")

#2
print("array a's second column and the last row: ", a[1:2,:] , a[3,:])
print("----------------------")

#3
print("all elements greater than mean: " , a[a > a.mean()]) # all elements greater than mean of all elements
print("----------------------")

#4
b= np.ones(4)

print("array b: \n" , b)
print("----------------------")

print("array a + array b: \n" , a+b)                      #broadcasting


array a: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
----------------------
array a's shape:  (4, 4)
----------------------
array a's type:  <class 'numpy.ndarray'>
----------------------
array's element a[0,0] type:  <class 'numpy.int64'>
----------------------
array a's second column and the last row:  [[5 6 7 8]] [13 14 15 16]
----------------------
all elements greater than mean:  [ 9 10 11 12 13 14 15 16]
----------------------
array b: 
 [1. 1. 1. 1.]
----------------------
array a + array b: 
 [[ 2.  3.  4.  5.]
 [ 6.  7.  8.  9.]
 [10. 11. 12. 13.]
 [14. 15. 16. 17.]]
